version: "3.5"

services:
  postgresql:
    image: postgres:12.3
    volumes:
      - ./config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "15432:5432"

  backend-development:
    build:
      context: ./atcoder-problems-backend
      dockerfile: Dockerfile.dev
    environment:
      SQL_URL: postgres://db_user:db_pass@postgresql:5432/test_db
      DATABASE_URL: postgres://db_user:db_pass@postgresql:5432/test_db
      RUST_LOG: info
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    volumes:
      - ./:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/atcoder-problems-backend/target
    working_dir: /app/atcoder-problems-backend
    command: /bin/sh -c "cargo watch -s 'cargo run --bin run_server'"

  frontend-development:
    image: node:20
    ports:
      - "3000:3000"
    environment:
      # Node 17でOpenSSLがデフォルトでMD4ハッシュを提供しなくなり、
      # これに依存していたwebpackに依存するreact-scripts 4.x系でのビルドができなくなってしまった。
      # --openssl-legacy-providerをオプションとして渡すことで、Node 17以降でもビルドができる。
      # react-scripts 4.x系から移行したら、このオプションは不要になる。
      NODE_OPTIONS: --openssl-legacy-provider
    volumes:
      - ./:/app
      - node_modules:/app/atcoder-problems-frontend/node_modules
    working_dir: /app/atcoder-problems-frontend
    command: /bin/sh -c "yarn && yarn start"

volumes:
  cargo-cache: null
  target-cache: null
  node_modules: null
